name: Main workflow

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      LOCAL_VERSION_NUMBER_FILE: build_version.txt
    steps:
    - name: Check out the project
      uses: actions/checkout@v2.3.2
    - name: Set up Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 12.x
    - name: Set up AWS command line interface
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2.1.0
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-
    - id: read_package_json
      name: Read package.json
      run: |
        package=`cat ./package.json`
        echo "The JSON file's contents are:"
        echo "$package"
        package="${package//'%'/'%25'}"
        package="${package//$'\n'/'%0A'}"
        package="${package//$'\r'/'%0D'}"
        echo "::set-output name=package_json::$package"
    - id: read_package_version
      name: Read version from package.json
      run: |
        package_version="${{ fromJSON(steps.read_package_json.outputs.package_json).version }}"
        echo "The version got from the value JSON file is $package_version"
        echo "::set-output name=package_version::$package_version"
    - id: development_version
      name: Determine development version
      run: |
        set +e
        aws s3api head-object --bucket anthem-workflows --key $(echo "${{ github.repository }}" | tr - _)/${PACKAGE_VERSION}_version.txt
        if [ $? -eq 0 ]; then
          aws s3 cp s3://anthem-workflows/$(echo "${{ github.repository }}" | tr - _)/${PACKAGE_VERSION}_version.txt $LOCAL_VERSION_NUMBER_FILE
        else
          echo 0 > $LOCAL_VERSION_NUMBER_FILE
        fi
        set -e
        dev_version=`cat $LOCAL_VERSION_NUMBER_FILE`
        echo "The development version number is $dev_version"
        rm $LOCAL_VERSION_NUMBER_FILE
        expr $dev_version + 1 > $LOCAL_VERSION_NUMBER_FILE
        dev_version=`cat $LOCAL_VERSION_NUMBER_FILE`
        echo "The development version number for the current run is $dev_version"
        echo "::set-output name=development_version::$dev_version"
      env:
        PACKAGE_VERSION: ${{ steps.read_package_version.outputs.package_version }}
    - name: Upload development version
      run: |
        set +e
        aws s3api head-object --bucket anthem-workflows --key $(echo "${{ github.repository }}" | tr - _)/${PACKAGE_VERSION}_version.txt
        if [ $? -eq 0 ]; then
          aws s3 rm s3://anthem-workflows/$(echo "${{ github.repository }}" | tr - _)/${PACKAGE_VERSION}_version.txt
        fi
        set -e
        aws s3 cp $LOCAL_VERSION_NUMBER_FILE s3://anthem-workflows/$(echo "${{ github.repository }}" | tr - _)/${PACKAGE_VERSION}_version.txt
      env:
        PACKAGE_VERSION: ${{ steps.read_package_version.outputs.package_version }}
    - id: version
      name: Determine version
      run: |
        version="${PACKAGE_VERSION/-dev/-dev.$DEVELOPMENT_VERSION_NUMBER}"
        echo "The version of the project is $version"
        echo "::set-output name=version::$version"
      env:
        PACKAGE_VERSION: ${{ steps.read_package_version.outputs.package_version }}
        DEVELOPMENT_VERSION_NUMBER: ${{ steps.development_version.outputs.development_version }}
    - name: Set development version to package.json
      run: sed -i "s/$PACKAGE_VERSION/${{ steps.version.outputs.version }}/g" package.json
      env:
        PACKAGE_VERSION: ${{ steps.read_package_version.outputs.package_version }}
    - name: Install dependencies
      run: npm install
    - name: Run linter
      run: npm run lint
    - name: Check formatting
      run: npm run format-check
    - name: Compile
      run: npm run build && npm run package
    - name: Run tests
      run: npm run test
    - name: Upload build artefacts
      uses: actions/upload-artifact@v2.1.3
      with:
        name: maintain-revision-${{ steps.version.outputs.version }}
        path: dist/
