name: Main workflow

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  LOCAL_VERSION_NUMBER_FILE: build_version.txt

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2.3.4

    - name: Set up Node.js environment
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 12.x

    - name: Determine the project’s version
      id: version
      uses: visiosto/maintain-revision@develop
      with:
        bucket: 'visiosto-workflows'
        type: npm
        upload: false

    - name: Replace the project’s version
      id: version
      uses: visiosto/replace-value@develop
      with:
        file: 'package.json'
        replaced: '-dev"'
        value: '-dev.${{ steps.version.outputs.revision-number }}"'

    - name: Get Yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache dependencies
      uses: actions/cache@v2.1.5
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Cache dependencies
      uses: actions/cache@v2.1.5
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run checks
      run: yarn ci-check

    - name: Run tests
      run: yarn test

  build:
    name: Build
    needs: [check]
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2.3.4

    - name: Set up Node.js environment
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 12.x

    - name: Determine the project’s version
      id: version
      uses: visiosto/maintain-revision@develop
      with:
        bucket: 'visiosto-workflows'
        type: npm

    - name: Replace the project’s version
      id: version
      uses: visiosto/replace-value@develop
      with:
        file: 'package.json'
        replaced: '-dev"'
        value: '-dev.${{ steps.version.outputs.revision-number }}"'

    - name: Get Yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache dependencies
      uses: actions/cache@v2.1.5
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Cache dependencies
      uses: actions/cache@v2.1.5
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Compile
      run: yarn clean && yarn build

    - name: Upload build artefacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: maintain-revision-${{ steps.version.outputs.version }}
        path: dist/
